name: Build Linux

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-4-dev libwebkitgtk-6.0-dev

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build KEXE
        run: ./gradlew compose-native:packageDistribution

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: compose-native/build/*.kexe
          retention-days: 5