name: Build Windows

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build EXE
        run: ./gradlew compose-native:packageDistribution

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: compose-native/build/*.exe
          retention-days: 5